app.dashboard:
    path: /
    controller: App\Controller\DashboardController:index

app.devices:
    path: /devices
    controller: App\Controller\DashboardController:devices

app.tags:
    path: /tags
    controller: App\Controller\DashboardController:tags

app.scenes:
    path: /scenes
    controller: App\Controller\DashboardController:scenes

app.scenes.call:
    path: /scenes/{scene}/call
    controller: App\Controller\DashboardController:calls

app.api:
    path: /api
    controller: App\Controller\DashboardController:api

api.scene.trigger:
    path: /api/scene/{slug}
    controller: App\Controller\Api\SceneController:trigger

api.yeelight.execute:
    path: /api/yeelight/{target}/{method}/{params?0}/{responseId<\d+>?0}
    controller: App\Controller\Api\YeelightController:execute
